# Dados

Estrutura dos dados: (parte mais densa tecnicamente)
* importar os dados com o pacote pandas (3 bases de dados diferentes)
* incorporar as 3 bases de dados em uma tabela só 
* aprimorar a organização da tabela 
* pegar dados (primeiro os obrigatórios) da tabela
* apresentar eles de forma informativa (talvez gráficos)

In [57]:
import pandas as pd 

#não importei do kaggle, não consegui e não sei se dá pra abrir em qualquer pc sem ter nada instalado

url="https://github.com/talissonmeira/WTH/blob/main/WtoData.csv?raw=true"

df_wt = pd.read_csv(url,encoding='latin-1',low_memory=False)

Os dados foram importados de um repositório público que eu criei no GitHub.

In [59]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns',25)
df_wt.head()

,Indicator Category,Indicator Code,Indicator,Reporting Economy Code,Reporting Economy ISO3A Code,Reporting Economy,Partner Economy Code,Partner Economy ISO3A Code,Partner Economy,Product/Sector Classification Code,Product/Sector Classification,Product/Sector Code,Product/Sector,Period Code,Period,Frequency Code,Frequency,Unit Code,Unit,Year,Value Flag Code,Value Flag,Text Value,Value
0,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,NaN,NaN,NaN,126.432
1,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,004,AFG,Afghanistan,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,85.260
2,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,008,ALB,Albania,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,NaN,NaN,NaN,138.571
3,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,012,DZA,Algeria,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,104.676
4,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,016,ASM,American Samoa,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,101.862

In [53]:
url2="https://raw.githubusercontent.com/talissonmeira/WTH/main/gdp_per_c.csv"

df_gdp = pd.read_csv(url2)

In [50]:
df_gdp

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.637989e+09,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.310056e+09,2.496648e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129059e+10,2.180847e+10,2.370702e+10,2.821004e+10,2.611879e+10,2.968217e+10,3.223912e+10,3.351455e+10,...,9.644185e+11,9.730435e+11,9.839370e+11,1.003679e+12,9.242525e+11,8.823551e+11,1.020647e+12,9.910223e+11,9.975340e+11,9.216459e+11,1.082096e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,...,1.780511e+10,1.990732e+10,2.014640e+10,2.049713e+10,1.913421e+10,1.811656e+10,1.875347e+10,1.805323e+10,1.879945e+10,2.011614e+10,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,1.583259e+10,1.442604e+10,...,6.709830e+11,7.275704e+11,8.207927e+11,8.649905e+11,7.607345e+11,6.905464e+11,6.837487e+11,7.416899e+11,7.945430e+11,7.844457e+11,8.358084e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.094365e+11,1.249982e+11,1.334016e+11,1.372444e+11,8.721929e+10,4.984049e+10,6.897276e+10,7.779294e+10,6.930910e+10,5.361907e+10,7.254699e+10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.341737e+09,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.007159e+09,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.272642e+10,3.540134e+10,4.041524e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,4.582015e+11,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.048421e+11,3.879346e+11,3.354421e+11,4.199464e+11,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,...,2.345952e+10,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,...,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10,NaN

In [ ]:
url3=''