# Dados

Estrutura dos dados: (parte mais densa tecnicamente)
* importar os dados com o pacote pandas (3 bases de dados diferentes)
* incorporar as 3 bases de dados em uma tabela só 
* aprimorar a organização da tabela 
* pegar dados (primeiro os obrigatórios) da tabela
* apresentar eles de forma informativa (talvez gráficos)

In [56]:
import pandas as pd 
import html5lib

#não importei do kaggle, não consegui e não sei se dá pra abrir em qualquer pc sem ter nada instalado

url="https://github.com/talissonmeira/WTD/blob/main/WtoMetadata_20221014064149.csv?raw=true"

df_data = pd.read_csv(url,error_bad_lines=False)

C:\Users\Dell\AppData\Local\Temp\ipykernel_11416\153103460.py:8: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df_data = pd.read_csv(url,error_bad_lines=False)
Skipping line 2090: expected 21 fields, saw 24
Skipping line 3312: expected 21 fields, saw 22
Skipping line 3379: expected 21 fields, saw 22

Os dados foram importados de um repositório público que eu criei no GitHub. As linhas com problemas foram substituídas por falsas, como são apenas 3 linhas em meio a 3 mil não vejo muito problema

In [58]:
pd.set_option('display.max_rows', 4)
df_data

,Indicator Category,Indicator Code,Indicator,Reporting Economy Code,Reporting Economy ISO3A Code,Reporting Economy,Partner Economy Code,Partner Economy ISO3A Code,Partner Economy,Product/Sector Classification Code,...,Product/Sector Code,Product/Sector,Period Code,Period,Frequency Code,Frequency,Unit Code,Unit,Category,Value
0,Trade in commercial services,ITS_CS_AM5,Commercial services imports by sector – annual...,090,SLB,Solomon Islands,000,NaN,World,BOP5,...,S200OS,Other commercial services (Commercial services...,-,-,-,-,USM,Million US dollar,Coverage,"Starting from 2009, data converted from BPM6 t..."
1,Trade in commercial services,ITS_CS_AX5,Commercial services exports by sector – annual...,702,SGP,Singapore,000,NaN,World,BOP5,...,S260,Financial services,-,-,-,-,USM,Million US dollar,Coverage,a) Includes FISIM (Financial Intermediation Se...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3641,Merchandise trade values,ITS_MTV_AM,Merchandise imports by product group – annual,201,NaN,Czech and Slovak Federal Republic,000,NaN,World,SITC3,...,MI,Fuels and mining products,-,-,-,-,USM,Million US dollar,Method of valuation,Imports are valued f.o.b.
3642,Merchandise trade values,ITS_MTV_AM,Merchandise imports by product group – annual,296,KIR,Kiribati,000,NaN,World,SITC3,...,MI,Fuels and mining products,-,-,-,-,USM,Million US dollar,Method of valuation,Until 2011: Imports are valued f.o.b.