# Dados

Estrutura dos dados: (parte mais densa tecnicamente)
* importar os dados com o pacote pandas (3 bases de dados diferentes)
* incorporar as 3 bases de dados em uma tabela só 
* aprimorar a organização da tabela 
* pegar dados (primeiro os obrigatórios) da tabela
* apresentar eles de forma informativa (talvez gráficos)

In [57]:
import pandas as pd 

#não importei do kaggle, não consegui e não sei se dá pra abrir em qualquer pc sem ter nada instalado

url="https://github.com/talissonmeira/WTH/blob/main/WtoData.csv?raw=true"

df_wt = pd.read_csv(url,encoding='latin-1',low_memory=False)

Os dados foram importados de um repositório público que eu criei no GitHub.

In [59]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns',25)
df_wt.head()
#dados de trading 2021-2022 que vai precisar agregar em grupos e somar os dados (todos de importação)

,Indicator Category,Indicator Code,Indicator,Reporting Economy Code,Reporting Economy ISO3A Code,Reporting Economy,Partner Economy Code,Partner Economy ISO3A Code,Partner Economy,Product/Sector Classification Code,Product/Sector Classification,Product/Sector Code,Product/Sector,Period Code,Period,Frequency Code,Frequency,Unit Code,Unit,Year,Value Flag Code,Value Flag,Text Value,Value
0,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,NaN,NaN,NaN,126.432
1,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,004,AFG,Afghanistan,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,85.260
2,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,008,ALB,Albania,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,NaN,NaN,NaN,138.571
3,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,012,DZA,Algeria,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,104.676
4,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,016,ASM,American Samoa,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,A,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,101.862

In [79]:
df_wt['Partner Economy'].value_counts()
#só pra ter uma ideia do que são os dados que estamos tratando

World                                             80302
European Union                                      516
Extra EU Trade                                      472
Extra Euro Area (19) Trade                          302
France                                              281
Germany                                             281
Netherlands                                         272
China                                               272
Chinese Taipei                                      271
Singapore                                           270
Japan                                               269
Italy                                               268
Australia                                           267
India                                               258
Thailand                                            254
Indonesia                                           254
New Zealand                                         253
Korea, Republic of                                  251
Canada                                              249
Mexico                                              245
Israel                                              244
Hong Kong, China                                    244
Spain                                               243
Portugal                                            241
Austria                                             241
Switzerland                                         240
Brazil                                              239
Ireland                                             238
Philippines                                         236
Saudi Arabia, Kingdom of                            234
Belgium                                             233
Norway                                              231
Sweden                                              231
Poland                                              228
Denmark                                             222
Romania                                             221
Türkiye                                             219
Luxembourg                                          219
Malaysia                                            217
Finland                                             216
Russian Federation                                  215
Morocco                                             212
Venezuela, Bolivarian Republic of                   212
Croatia                                             211
Argentina                                           209
Lithuania                                           209
South Africa                                        208
Greece                                              208
Colombia                                            202
Chile                                               201
Czech Republic                                      197
Bulgaria                                            196
Latvia                                              195
Slovak Republic                                     195
Cyprus                                              193
Hungary                                             192
Slovenia                                            188
Malta                                               186
Estonia                                             184
United Kingdom                                      183
Euro Area (19)                                      175
Brunei Darussalam                                   144
Peru                                                143
Viet Nam                                            140
Panama                                              134
Bahrain, Kingdom of                                 133
El Salvador                                         132
Nigeria                                             129
Jordan                                              126
Oman                                                124
Guatemala                                           123
Costa Rica                                          122
Dominican Republic                                  121
Bermuda                                             119
Honduras                                            119
Nicaragua                                           116
United States of America                            116
Pakistan                                            109
European Union (28)                                  96
Montenegro                                           90
Egypt                                                87
Iceland                                              80
Ukraine                                              80
Liechtenstein                                        77
Uruguay                                              77
Iran                                                 76
Albania                                              75
Belarus                                              74
Serbia                                               63
Association of Southeast Asian Nations (ASEAN)       24
Name: Partner Economy, dtype: int64

In [53]:
url2="https://raw.githubusercontent.com/talissonmeira/WTH/main/gdp_per_c.csv"

df_gdp = pd.read_csv(url2)

In [77]:
df_gdp
#dados do pib de cada país, já estão agregados. tanto aqui quanto nos outros é bom que a gente tire
#países com população muito pequena
#ano 2021

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.637989e+09,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.310056e+09,2.496648e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129059e+10,2.180847e+10,2.370702e+10,2.821004e+10,2.611879e+10,2.968217e+10,3.223912e+10,3.351455e+10,...,9.644185e+11,9.730435e+11,9.839370e+11,1.003679e+12,9.242525e+11,8.823551e+11,1.020647e+12,9.910223e+11,9.975340e+11,9.216459e+11,1.082096e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,...,1.780511e+10,1.990732e+10,2.014640e+10,2.049713e+10,1.913421e+10,1.811656e+10,1.875347e+10,1.805323e+10,1.879945e+10,2.011614e+10,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,1.583259e+10,1.442604e+10,...,6.709830e+11,7.275704e+11,8.207927e+11,8.649905e+11,7.607345e+11,6.905464e+11,6.837487e+11,7.416899e+11,7.945430e+11,7.844457e+11,8.358084e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.094365e+11,1.249982e+11,1.334016e+11,1.372444e+11,8.721929e+10,4.984049e+10,6.897276e+10,7.779294e+10,6.930910e+10,5.361907e+10,7.254699e+10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.341737e+09,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.007159e+09,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.272642e+10,3.540134e+10,4.041524e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,4.582015e+11,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.048421e+11,3.879346e+11,3.354421e+11,4.199464e+11,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,...,2.345952e+10,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,...,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10,NaN

In [75]:
url3='https://github.com/talissonmeira/WTH/blob/main/HDR21-22_Statistical_Annex_HDI_Trends_Table.xlsx?raw=true'
df_hdi = pd.read_excel(url3)

In [78]:
df_hdi.head(100)
#dados de uma tabela do excel, por isso muitos espaços nulos 
# ano de 2021
#tirado do Human Delepment Reports da UNDP (united nations development programme)

,Back,"Table 2. Human Development Index trends, 1990-2021",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Human Development Index (HDI),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Change in HDI rank,NaN,Average annual HDI growth,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,(%),NaN,NaN,NaN,NaN,NaN,NaN
3,HDI rank,Country,1990,NaN,2000,NaN,2010,NaN,2015,NaN,2018,NaN,...,NaN,2021,NaN,2015-2021,a,1990-2000,NaN,2000-2010,NaN,2010-2021,NaN,1990-2021
4,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,Switzerland,0.851,NaN,0.887,NaN,0.942,NaN,0.954,NaN,0.959,NaN,...,NaN,0.962,NaN,0,NaN,0.415188,NaN,0.603416,NaN,0.191175,NaN,0.396274
6,2,Norway,0.838,NaN,0.913,NaN,0.941,NaN,0.953,NaN,0.962,NaN,...,NaN,0.961,NaN,0,NaN,0.860862,NaN,0.302529,NaN,0.191376,NaN,0.442772
7,3,Iceland,0.811,NaN,0.871,NaN,0.902,NaN,0.945,NaN,0.959,NaN,...,NaN,0.959,NaN,0,NaN,0.716292,NaN,0.350338,NaN,0.558614,NaN,0.542184
8,4,"Hong Kong, China (SAR)",0.788,NaN,0.851,NaN,0.907,NaN,0.935,NaN,0.949,NaN,...,NaN,0.952,NaN,3,NaN,0.772106,NaN,0.639338,NaN,0.441176,NaN,0.611757
9,5,Australia,0.865,NaN,0.896,NaN,0.923,NaN,0.933,NaN,0.941,NaN,...,NaN,0.951,NaN,3,NaN,0.35273,NaN,0.297329,NaN,0.27205,NaN,0.306225
10,6,Denmark,0.834,NaN,0.889,NaN,0.913,NaN,0.936,NaN,0.942,NaN,...,NaN,0.948,NaN,0,NaN,0.640682,NaN,0.266742,NaN,0.342573,NaN,0.414149
11,7,Sweden,0.81,NaN,0.904,NaN,0.91,NaN,0.937,NaN,0.942,NaN,...,NaN,0.947,NaN,-2,NaN,1.104001,NaN,0.066174,NaN,0.362971,NaN,0.505353
12,8,Ireland,0.737,NaN,0.847,NaN,0.904,NaN,0.925,NaN,0.937,NaN,...,NaN,0.945,NaN,6,NaN,1.400849,NaN,0.653412,NaN,0.404047,NaN,0.80515
13,9,Germany,0.829,NaN,0.889,NaN,0.926,NaN,0.938,NaN,0.945,NaN,...,NaN,0.942,NaN,-5,NaN,0.701218,NaN,0.408603,NaN,0.155858,NaN,0.413061
14,10,Netherlands,0.847,NaN,0.893,NaN,0.917,NaN,0.932,NaN,0.939,NaN,...,NaN,0.941,NaN,-1,NaN,0.53026,NaN,0.265561,NaN,0.235146,NaN,0.340069
15,11,Finland,0.814,NaN,0.891,NaN,0.911,NaN,0.93,NaN,0.936,NaN,...,NaN,0.94,NaN,0,NaN,0.907938,NaN,0.222231,NaN,0.285288,NaN,0.465336
16,12,Singapore,0.727,NaN,0.831,NaN,0.91,NaN,0.93,NaN,0.94,NaN,...,NaN,0.939,NaN,-1,NaN,1.346011,NaN,0.912284,NaN,0.285597,NaN,0.828865
17,13,Belgium,0.816,NaN,0.887,NaN,0.912,NaN,0.924,NaN,0.933,NaN,...,NaN,0.937,NaN,2,NaN,0.837796,NaN,0.278337,NaN,0.246151,NaN,0.447025
18,13,New Zealand,0.806,NaN,0.887,NaN,0.922,NaN,0.931,NaN,0.936,NaN,...,NaN,0.937,NaN,-3,NaN,0.962212,NaN,0.387752,NaN,0.146817,NaN,0.486987
19,15,Canada,0.86,NaN,0.89,NaN,0.911,NaN,0.926,NaN,0.933,NaN,...,NaN,0.936,NaN,-2,NaN,0.343479,NaN,0.233487,NaN,0.246417,NaN,0.273545
20,16,Liechtenstein,..,NaN,0.873,NaN,0.913,NaN,0.924,NaN,0.928,NaN,...,NaN,0.935,NaN,-1,NaN,..,NaN,0.449008,NaN,0.216695,NaN,..
21,17,Luxembourg,0.786,NaN,0.864,NaN,0.912,NaN,0.915,NaN,0.922,NaN,...,NaN,0.93,NaN,3,NaN,0.95065,NaN,0.542136,NaN,0.177836,NaN,0.544145
22,18,United Kingdom,0.804,NaN,0.862,NaN,0.912,NaN,0.924,NaN,0.929,NaN,...,NaN,0.929,NaN,-3,NaN,0.698992,NaN,0.56544,NaN,0.168039,NaN,0.467248
23,19,Japan,0.845,NaN,0.877,NaN,0.898,NaN,0.918,NaN,0.923,NaN,...,NaN,0.925,NaN,0,NaN,0.372395,NaN,0.236911,NaN,0.269669,NaN,0.292223
24,19,Korea (Republic of),0.737,NaN,0.825,NaN,0.89,NaN,0.909,NaN,0.919,NaN,...,NaN,0.925,NaN,3,NaN,1.13434,NaN,0.761264,NaN,0.351273,NaN,0.735615
25,21,United States,0.872,NaN,0.891,NaN,0.911,NaN,0.92,NaN,0.927,NaN,...,NaN,0.921,NaN,-3,NaN,0.215783,NaN,0.222231,NaN,0.099296,NaN,0.176512
26,22,Israel,0.787,NaN,0.844,NaN,0.894,NaN,0.909,NaN,0.919,NaN,...,NaN,0.919,NaN,0,NaN,0.701693,NaN,0.577192,NaN,0.251045,NaN,0.50144
27,23,Malta,0.73,NaN,0.779,NaN,0.861,NaN,0.889,NaN,0.91,NaN,...,NaN,0.918,NaN,4,NaN,0.65178,NaN,1.00586,NaN,0.584455,NaN,0.741942
28,23,Slovenia,..,NaN,0.821,NaN,0.89,NaN,0.903,NaN,0.917,NaN,...,NaN,0.918,NaN,1,NaN,..,NaN,0.810248,NaN,0.281996,NaN,..
29,25,Austria,0.825,NaN,0.871,NaN,0.902,NaN,0.91,NaN,0.917,NaN,...,NaN,0.916,NaN,-4,NaN,0.544061,NaN,0.350338,NaN,0.140115,NaN,0.338096
30,26,United Arab Emirates,0.728,NaN,0.796,NaN,0.835,NaN,0.865,NaN,0.909,NaN,...,NaN,0.911,NaN,9,NaN,0.89698,NaN,0.479471,NaN,0.795064,NaN,0.725983
31,27,Spain,0.757,NaN,0.825,NaN,0.868,NaN,0.889,NaN,0.901,NaN,...,NaN,0.905,NaN,0,NaN,0.863912,NaN,0.509376,NaN,0.380205,NaN,0.5777
32,28,France,0.791,NaN,0.844,NaN,0.877,NaN,0.892,NaN,0.901,NaN,...,NaN,0.903,NaN,-3,NaN,0.650653,NaN,0.384281,NaN,0.265949,NaN,0.42809
33,29,Cyprus,0.716,NaN,0.797,NaN,0.857,NaN,0.871,NaN,0.892,NaN,...,NaN,0.896,NaN,3,NaN,1.077509,NaN,0.728473,NaN,0.405388,NaN,0.726043
34,30,Italy,0.778,NaN,0.841,NaN,0.882,NaN,0.882,NaN,0.893,NaN,...,NaN,0.895,NaN,-1,NaN,0.781691,NaN,0.477139,NaN,0.133104,NaN,0.452949
35,31,Estonia,0.732,NaN,0.787,NaN,0.861,NaN,0.882,NaN,0.891,NaN,...,NaN,0.89,NaN,-2,NaN,0.727108,NaN,0.902713,NaN,0.301608,NaN,0.632446
36,32,Czechia,0.742,NaN,0.808,NaN,0.87,NaN,0.891,NaN,0.894,NaN,...,NaN,0.889,NaN,-6,NaN,0.855769,NaN,0.742051,NaN,0.196593,NaN,0.584761
37,33,Greece,0.759,NaN,0.81,NaN,0.869,NaN,0.88,NaN,0.886,NaN,...,NaN,0.887,NaN,-2,NaN,0.652444,NaN,0.705566,NaN,0.186554,NaN,0.503986
38,34,Poland,0.716,NaN,0.793,NaN,0.841,NaN,0.868,NaN,0.877,NaN,...,NaN,0.876,NaN,-1,NaN,1.026665,NaN,0.589415,NaN,0.371365,NaN,0.652721
39,35,Bahrain,0.742,NaN,0.798,NaN,0.808,NaN,0.858,NaN,0.879,NaN,...,NaN,0.875,NaN,3,NaN,0.730247,NaN,0.124612,NaN,0.726827,NaN,0.533271
40,35,Lithuania,0.734,NaN,0.766,NaN,0.842,NaN,0.862,NaN,0.88,NaN,...,NaN,0.875,NaN,1,NaN,0.427643,NaN,0.950467,NaN,0.350101,NaN,0.568432
41,35,Saudi Arabia,0.678,NaN,0.737,NaN,0.816,NaN,0.859,NaN,0.865,NaN,...,NaN,0.875,NaN,2,NaN,0.837897,NaN,1.023467,NaN,0.63665,NaN,0.826222
42,38,Portugal,0.701,NaN,0.791,NaN,0.829,NaN,0.85,NaN,0.86,NaN,...,NaN,0.866,NaN,2,NaN,1.215225,NaN,0.470324,NaN,0.397741,NaN,0.684191
43,39,Latvia,0.73,NaN,0.756,NaN,0.824,NaN,0.85,NaN,0.866,NaN,...,NaN,0.863,NaN,1,NaN,0.350582,NaN,0.865011,NaN,0.421286,NaN,0.541364
44,40,Andorra,..,NaN,0.818,NaN,0.848,NaN,0.867,NaN,0.872,NaN,...,NaN,0.858,NaN,-6,NaN,..,NaN,0.360832,NaN,0.106634,NaN,..
45,40,Croatia,..,NaN,0.759,NaN,0.821,NaN,0.843,NaN,0.856,NaN,...,NaN,0.858,NaN,5,NaN,..,NaN,0.788304,NaN,0.40154,NaN,..
46,42,Chile,0.706,NaN,0.763,NaN,0.813,NaN,0.846,NaN,0.856,NaN,...,NaN,0.855,NaN,1,NaN,0.77945,NaN,0.636749,NaN,0.458962,NaN,0.619609
47,42,Qatar,0.758,NaN,0.801,NaN,0.834,NaN,0.846,NaN,0.853,NaN,...,NaN,0.855,NaN,1,NaN,0.553301,NaN,0.404541,NaN,0.226329,NaN,0.389201
48,44,San Marino,..,NaN,..,NaN,..,NaN,..,NaN,0.86,NaN,...,NaN,0.853,NaN,..,NaN,..,NaN,..,NaN,..,NaN,..
49,45,Slovakia,0.692,NaN,0.763,NaN,0.84,NaN,0.851,NaN,0.859,NaN,...,NaN,0.848,NaN,-5,NaN,0.981506,NaN,0.966075,NaN,0.086208,NaN,0.657944
50,46,Hungary,0.72,NaN,0.773,NaN,0.828,NaN,0.838,NaN,0.849,NaN,...,NaN,0.846,NaN,1,NaN,0.712807,NaN,0.689709,NaN,0.195702,NaN,0.521575
51,47,Argentina,0.723,NaN,0.779,NaN,0.834,NaN,0.848,NaN,0.85,NaN,...,NaN,0.842,NaN,-4,NaN,0.748808,NaN,0.684556,NaN,0.086825,NaN,0.492729
52,48,Türkiye,0.6,NaN,0.67,NaN,0.749,NaN,0.817,NaN,0.839,NaN,...,NaN,0.838,NaN,6,NaN,1.109591,NaN,1.120848,NaN,1.025946,NaN,1.083533
53,49,Montenegro,..,NaN,..,NaN,0.808,NaN,0.822,NaN,0.834,NaN,...,NaN,0.832,NaN,3,NaN,..,NaN,..,NaN,0.266449,NaN,..
54,50,Kuwait,0.718,NaN,0.787,NaN,0.813,NaN,0.83,NaN,0.836,NaN,...,NaN,0.831,NaN,-1,NaN,0.92181,NaN,0.325557,NaN,0.199277,NaN,0.472598
55,51,Brunei Darussalam,0.77,NaN,0.808,NaN,0.828,NaN,0.836,NaN,0.83,NaN,...,NaN,0.829,NaN,-3,NaN,0.482878,NaN,0.24481,NaN,0.010973,NaN,0.238444
56,52,Russian Federation,0.743,NaN,0.732,NaN,0.796,NaN,0.824,NaN,0.841,NaN,...,NaN,0.822,NaN,-2,NaN,-0.149044,NaN,0.841709,NaN,0.29262,NaN,0.326481
57,53,Romania,0.703,NaN,0.715,NaN,0.807,NaN,0.813,NaN,0.827,NaN,...,NaN,0.821,NaN,3,NaN,0.1694,NaN,1.217766,NaN,0.156481,NaN,0.501791
58,54,Oman,..,NaN,0.705,NaN,0.788,NaN,0.823,NaN,0.834,NaN,...,NaN,0.816,NaN,-3,NaN,..,NaN,1.11922,NaN,0.317925,NaN,..
59,55,Bahamas,..,NaN,0.799,NaN,0.812,NaN,0.82,NaN,0.827,NaN,...,NaN,0.812,NaN,-2,NaN,..,NaN,0.161524,NaN,0,NaN,..
60,56,Kazakhstan,0.673,NaN,0.68,NaN,0.767,NaN,0.805,NaN,0.814,NaN,...,NaN,0.811,NaN,4,NaN,0.103528,NaN,1.211217,NaN,0.50839,NaN,0.6035
61,57,Trinidad and Tobago,0.66,NaN,0.712,NaN,0.79,NaN,0.816,NaN,0.815,NaN,...,NaN,0.81,NaN,-2,NaN,0.761264,NaN,1.044972,NaN,0.227543,NaN,0.662814
62,58,Costa Rica,0.66,NaN,0.71,NaN,0.772,NaN,0.798,NaN,0.811,NaN,...,NaN,0.809,NaN,4,NaN,0.732924,NaN,0.84071,NaN,0.426492,NaN,0.658803
63,58,Uruguay,0.701,NaN,0.753,NaN,0.787,NaN,0.811,NaN,0.819,NaN,...,NaN,0.809,NaN,0,NaN,0.71814,NaN,0.442607,NaN,0.250957,NaN,0.463299
64,60,Belarus,..,NaN,0.712,NaN,0.79,NaN,0.812,NaN,0.818,NaN,...,NaN,0.808,NaN,-3,NaN,..,NaN,1.044972,NaN,0.20502,NaN,..
65,61,Panama,0.669,NaN,0.721,NaN,0.773,NaN,0.8,NaN,0.814,NaN,...,NaN,0.805,NaN,0,NaN,0.751359,NaN,0.69883,NaN,0.369437,NaN,0.598747
66,62,Malaysia,0.64,NaN,0.721,NaN,0.769,NaN,0.797,NaN,0.807,NaN,...,NaN,0.803,NaN,1,NaN,1.198839,NaN,0.6466,NaN,0.394081,NaN,0.734577
67,63,Georgia,..,NaN,0.702,NaN,0.759,NaN,0.79,NaN,0.804,NaN,...,NaN,0.802,NaN,7,NaN,..,NaN,0.783739,NaN,0.502228,NaN,..
68,63,Mauritius,0.626,NaN,0.681,NaN,0.755,NaN,0.795,NaN,0.811,NaN,...,NaN,0.802,NaN,2,NaN,0.845675,NaN,1.036893,NaN,0.550518,NaN,0.802422
69,63,Serbia,..,NaN,0.69,NaN,0.767,NaN,0.794,NaN,0.808,NaN,...,NaN,0.802,NaN,4,NaN,..,NaN,1.063568,NaN,0.406477,NaN,..
70,66,Thailand,0.576,NaN,0.653,NaN,0.737,NaN,0.781,NaN,0.795,NaN,...,NaN,0.8,NaN,6,NaN,1.262599,NaN,1.217459,NaN,0.748458,NaN,1.065325
71,NaN,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,67,Albania,0.647,NaN,0.677,NaN,0.754,NaN,0.795,NaN,0.806,NaN,...,NaN,0.796,NaN,-2,NaN,0.454279,NaN,1.083034,NaN,0.494005,NaN,0.670798
73,68,Bulgaria,0.684,NaN,0.725,NaN,0.79,NaN,0.809,NaN,0.809,NaN,...,NaN,0.795,NaN,-9,NaN,0.583835,NaN,0.86231,NaN,0.057373,NaN,0.486289
74,68,Grenada,..,NaN,..,NaN,0.782,NaN,0.79,NaN,0.797,NaN,...,NaN,0.795,NaN,2,NaN,..,NaN,..,NaN,0.149998,NaN,..
75,70,Barbados,0.725,NaN,0.756,NaN,0.788,NaN,0.791,NaN,0.797,NaN,...,NaN,0.79,NaN,-2,NaN,0.419575,NaN,0.415428,NaN,0.023047,NaN,0.277356
76,71,Antigua and Barbuda,..,NaN,..,NaN,0.79,NaN,0.791,NaN,0.798,NaN,...,NaN,0.788,NaN,-3,NaN,..,NaN,..,NaN,-0.023041,NaN,..
77,72,Seychelles,..,NaN,0.744,NaN,0.776,NaN,0.796,NaN,0.8,NaN,...,NaN,0.785,NaN,-8,NaN,..,NaN,0.422003,NaN,0.104884,NaN,..
78,73,Sri Lanka,0.636,NaN,0.688,NaN,0.737,NaN,0.764,NaN,0.776,NaN,...,NaN,0.782,NaN,9,NaN,0.788999,NaN,0.690363,NaN,0.540244,NaN,0.66886
79,74,Bosnia and Herzegovina,..,NaN,0.667,NaN,0.725,NaN,0.761,NaN,0.776,NaN,...,NaN,0.78,NaN,10,NaN,..,NaN,0.837302,NaN,0.666962,NaN,..
80,75,Saint Kitts and Nevis,..,NaN,..,NaN,0.759,NaN,0.772,NaN,0.779,NaN,...,NaN,0.777,NaN,2,NaN,..,NaN,..,NaN,0.213305,NaN,..
81,76,Iran (Islamic Republic of),0.601,NaN,0.685,NaN,0.745,NaN,0.776,NaN,0.787,NaN,...,NaN,0.774,NaN,-2,NaN,1.316834,NaN,0.843189,NaN,0.347764,NaN,0.819393
82,77,Ukraine,0.729,NaN,0.7,NaN,0.764,NaN,0.774,NaN,0.783,NaN,...,NaN,0.773,NaN,-2,NaN,-0.405111,NaN,0.878713,NaN,0.106523,NaN,0.189228
83,78,North Macedonia,..,NaN,0.675,NaN,0.738,NaN,0.762,NaN,0.779,NaN,...,NaN,0.77,NaN,5,NaN,..,NaN,0.896304,NaN,0.386624,NaN,..
84,79,China,0.484,NaN,0.584,NaN,0.691,NaN,0.733,NaN,0.755,NaN,...,NaN,0.768,NaN,19,NaN,1.895909,NaN,1.69662,NaN,0.965081,NaN,1.500517
85,80,Dominican Republic,0.577,NaN,0.646,NaN,0.708,NaN,0.736,NaN,0.764,NaN,...,NaN,0.767,NaN,16,NaN,1.135976,NaN,0.920658,NaN,0.730315,NaN,0.922437
86,80,Moldova (Republic of),0.653,NaN,0.641,NaN,0.73,NaN,0.749,NaN,0.768,NaN,...,NaN,0.767,NaN,9,NaN,-0.185305,NaN,1.308639,NaN,0.450487,NaN,0.520413
87,80,Palau,..,NaN,0.739,NaN,0.773,NaN,0.78,NaN,0.778,NaN,...,NaN,0.767,NaN,-7,NaN,..,NaN,0.450824,NaN,-0.070814,NaN,..
88,83,Cuba,0.68,NaN,0.693,NaN,0.78,NaN,0.773,NaN,0.783,NaN,...,NaN,0.764,NaN,-7,NaN,0.189551,NaN,1.18966,NaN,-0.188242,NaN,0.376433
89,84,Peru,0.621,NaN,0.676,NaN,0.725,NaN,0.759,NaN,0.776,NaN,...,NaN,0.762,NaN,1,NaN,0.852231,NaN,0.70224,NaN,0.453524,NaN,0.662233
90,85,Armenia,0.656,NaN,0.662,NaN,0.746,NaN,0.766,NaN,0.771,NaN,...,NaN,0.759,NaN,-5,NaN,0.091089,NaN,1.201764,NaN,0.15718,NaN,0.471563
91,86,Mexico,0.662,NaN,0.709,NaN,0.746,NaN,0.768,NaN,0.777,NaN,...,NaN,0.758,NaN,-8,NaN,0.688257,NaN,0.509997,NaN,0.145176,NaN,0.437787
92,87,Brazil,0.61,NaN,0.679,NaN,0.723,NaN,0.753,NaN,0.764,NaN,...,NaN,0.754,NaN,1,NaN,1.077384,NaN,0.629856,NaN,0.382394,NaN,0.685998
93,88,Colombia,0.61,NaN,0.666,NaN,0.726,NaN,0.754,NaN,0.763,NaN,...,NaN,0.752,NaN,-1,NaN,0.882176,NaN,0.866335,NaN,0.320388,NaN,0.677372
94,89,Saint Vincent and the Grenadines,..,NaN,0.683,NaN,0.734,NaN,0.759,NaN,0.775,NaN,...,NaN,0.751,NaN,-4,NaN,..,NaN,0.722741,NaN,0.208368,NaN,..
95,90,Maldives,..,NaN,0.628,NaN,0.688,NaN,0.736,NaN,0.75,NaN,...,NaN,0.747,NaN,6,NaN,..,NaN,0.916663,NaN,0.750771,NaN,..
96,91,Algeria,0.591,NaN,0.649,NaN,0.721,NaN,0.74,NaN,0.745,NaN,...,NaN,0.745,NaN,2,NaN,0.940563,NaN,1.057618,NaN,0.298126,NaN,0.749791
97,91,Azerbaijan,..,NaN,0.622,NaN,0.727,NaN,0.748,NaN,0.757,NaN,...,NaN,0.745,NaN,-1,NaN,..,NaN,1.572093,NaN,0.22259,NaN,..
98,91,Tonga,0.645,NaN,0.685,NaN,0.713,NaN,0.73,NaN,0.742,NaN,...,NaN,0.745,NaN,10,NaN,0.603499,NaN,0.401429,NaN,0.399914,NaN,0.466031
99,91,Turkmenistan,..,NaN,..,NaN,0.711,NaN,0.74,NaN,0.746,NaN,...,NaN,0.745,NaN,2,NaN,..,NaN,..,NaN,0.425556,NaN,..

In [149]:
columns_to_keep = ['Table 2. Human Development Index trends, 1990-2021', 'Unnamed: 16']
df_hdi2 = df_hdi[columns_to_keep]

df_hdi2.head()

  Table 2. Human Development Index trends, 1990-2021 Unnamed: 16
0                                                NaN         NaN
1                                                NaN         NaN
2                                                NaN         NaN
3                                            Country        2021
4                        VERY HIGH HUMAN DEVELOPMENT         NaN

a de se notar que há vários problemas na tabela, mas como iremos usar apenas os dados de 2021, não há problemas nisso.
daqui dá (e tem que) pegar vários detalhes da tabela (cabe gráficos)

In [97]:
df_wt['Indicator'].value_counts()
#como só precisamos dos dados de imp e exp total para entender a balança comercial:
#os dados que nos servem são Total merchandise exports e import (usar quarterly)

Commercial services exports by sector and partner  annual                17661
Commercial services imports by sector and partner  annual                15822
Commercial services exports of selected economies  monthly               10714
Commercial services imports of selected economies  monthly               10698
Commercial services imports by main sector  quarterly                     9507
Commercial services exports by main sector  quarterly                     9428
Commercial services exports of selected economies (growth)  monthly       6417
Commercial services imports of selected economies (growth)  monthly       6411
Total merchandise exports - monthly                                        1460
Total merchandise imports - monthly                                        1460
Merchandise export volume indices, not seasonally adjusted - quarterly      714
Merchandise import volume indices, not seasonally adjusted - quarterly      714
Total merchandise exports - quarterly                                       630
Total merchandise imports - quarterly                                       624
Merchandise import volume indices, seasonally adjusted - quarterly          366
Merchandise export volume indices, seasonally adjusted - quarterly          366
Merchandise import volume chained indices - annual                          270
Merchandise import volume fixed-base indices - annual                       270
Merchandise import volume change - annual                                   270
Merchandise export volume fixed-base indices - annual                       268
Merchandise export volume chained indices - annual                          268
Merchandise export volume change - annual                                   266
Merchandise imports by product group  annual                               264
Merchandise exports by product group  annual                               264
Merchandise import unit value chained indices - annual                      256
Merchandise import unit value fixed-base indices - annual                   256
Merchandise export unit value fixed-base indices - annual                   255
Merchandise export unit value chained indices - annual                      255
Merchandise import value chained indices - annual                           255
Merchandise import value fixed-base indices - annual                        255
Merchandise export value chained indices - annual                           254
Merchandise export value fixed-base indices - annual                        254
Export price indices of manufactured goods - monthly                        126
Export price changes of manufactured goods - monthly                        126
Import price changes of manufactured goods - monthly                        126
Import price indices of manufactured goods - monthly                        114
Name: Indicator, dtype: int64

In [153]:
df_wt2 = df_wt[df_wt['Indicator'].isin(['Total merchandise exports - quarterly','Total merchandise imports - quarterly'])]
df_wt2.head()

,Indicator Category,Indicator Code,Indicator,Reporting Economy Code,Reporting Economy ISO3A Code,Reporting Economy,Partner Economy Code,Partner Economy ISO3A Code,Partner Economy,Product/Sector Classification Code,Product/Sector Classification,Product/Sector Code,Product/Sector,Period Code,Period,Frequency Code,Frequency,Unit Code,Unit,Year,Value Flag Code,Value Flag,Text Value,Value
9752,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q1,First Quarter,Q,Quarterly,USM,Million US dollar,2022,NaN,NaN,NaN,6.160946e+06
9753,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q1,First Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,5.083166e+06
9754,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q2,Second Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,5.520799e+06
9755,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q2,Second Quarter,Q,Quarterly,USM,Million US dollar,2022,NaN,NaN,NaN,6.488575e+06
9756,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q3,Third Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,5.654873e+06

In [154]:
#agora a gente precisa filtrar os dados pra apenas 2021 e apenas de economias nacionais
#exluir 2022 e exluir 'world' 'europe' 'asia'
df_wt2 = df_wt2[df_wt2['Year'].isin([2021])]
df_wt2.head()

,Indicator Category,Indicator Code,Indicator,Reporting Economy Code,Reporting Economy ISO3A Code,Reporting Economy,Partner Economy Code,Partner Economy ISO3A Code,Partner Economy,Product/Sector Classification Code,Product/Sector Classification,Product/Sector Code,Product/Sector,Period Code,Period,Frequency Code,Frequency,Unit Code,Unit,Year,Value Flag Code,Value Flag,Text Value,Value
9753,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q1,First Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,5.083166e+06
9754,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q2,Second Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,5.520799e+06
9756,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q3,Third Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,5.654873e+06
9757,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,000,NaN,World,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q4,Fourth Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,6.148697e+06
9758,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,008,ALB,Albania,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q1,First Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,1.581366e+03

In [170]:
#agora pra excluir economias que não são países específicos:
#usar o Reporting Economy ISO3A Code	 que é nulo quando não é de país
#retirar a união europeia que é a única com código específico

df_wt2 = df_wt2.dropna(subset=['Reporting Economy ISO3A Code'])
df_wt2= df_wt2[~(df_wt2['Reporting Economy ISO3A Code']=='EEC')]
df_wt2.head()

,Indicator Category,Indicator Code,Indicator,Reporting Economy Code,Reporting Economy ISO3A Code,Reporting Economy,Partner Economy Code,Partner Economy ISO3A Code,Partner Economy,Product/Sector Classification Code,Product/Sector Classification,Product/Sector Code,Product/Sector,Period Code,Period,Frequency Code,Frequency,Unit Code,Unit,Year,Value Flag Code,Value Flag,Text Value,Value
9758,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,008,ALB,Albania,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q1,First Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,1581.365834
9761,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,008,ALB,Albania,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q2,Second Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,1882.155316
9762,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,008,ALB,Albania,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q3,Third Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,1948.507635
9763,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,008,ALB,Albania,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q4,Fourth Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,2306.054913
9765,Merchandise trade values,ITS_MTV_QM,Total merchandise imports - quarterly,012,DZA,Algeria,000,NaN,World,SITC3,Merchandise - SITC Revision 3 (aggregates),TO,Total merchandise,Q1,First Quarter,Q,Quarterly,USM,Million US dollar,2021,E,Estimate,NaN,8200.000000

In [172]:
df_wt2['Reporting Economy ISO3A Code'].value_counts()

ALB    8
NLD    8
POL    8
PHL    8
PER    8
PRY    8
PAN    8
PAK    8
NOR    8
NGA    8
NZL    8
MAR    8
ROM    8
MDA    8
MEX    8
MUS    8
MLT    8
MYS    8
LUX    8
LTU    8
LVA    8
LBN    8
PRT    8
RUS    8
KWT    8
TUR    8
SRB    8
VEN    8
URY    8
USA    8
TZA    8
GBR    8
EGY    8
MKD    8
UKR    8
TUN    8
SAU    8
THA    8
CHE    8
SWE    8
ESP    8
ZAF    8
SVN    8
VNM    8
SVK    8
SGP    8
KGZ    8
KOR    8
DZA    8
BLR    8
CYP    8
HRV    8
CRI    8
COL    8
CHT    8
CHN    8
CHL    8
LKA    8
CAN    8
BGR    8
DNK    8
BRA    8
BOL    8
BEL    8
ARM    8
BGD    8
BHR    8
AUT    8
AUS    8
ARG    8
CZE    8
DOM    8
KEN    8
ISL    8
JOR    8
KAZ    8
JPN    8
ITA    8
ISR    8
IRL    8
IRN    8
IDN    8
IND    8
HUN    8
ECU    8
HKG    8
HND    8
GTM    8
GRC    8
DEU    8
FRA    8
FIN    8
EST    8
SLV    8
IRQ    4
Name: Reporting Economy ISO3A Code, dtype: int64

In [175]:
#como podemos ver o iraque só tem 4 dados, o que significa que ta incompleto (vou tirar)
df_wt2= df_wt2[~(df_wt2['Reporting Economy ISO3A Code']=='IRQ')]
df_wt2['Reporting Economy ISO3A Code'].value_counts()

ALB    8
MAR    8
PHL    8
PER    8
PRY    8
PAN    8
PAK    8
NOR    8
NGA    8
NZL    8
NLD    8
MDA    8
PRT    8
MEX    8
MUS    8
MLT    8
MYS    8
LUX    8
LTU    8
LVA    8
LBN    8
KGZ    8
POL    8
ROM    8
DZA    8
TUN    8
VEN    8
URY    8
USA    8
TZA    8
GBR    8
EGY    8
MKD    8
UKR    8
TUR    8
THA    8
RUS    8
CHE    8
SWE    8
ESP    8
ZAF    8
SVN    8
VNM    8
SVK    8
SGP    8
SAU    8
KWT    8
KOR    8
KEN    8
BLR    8
CYP    8
HRV    8
CRI    8
COL    8
CHT    8
CHN    8
CHL    8
LKA    8
CAN    8
BGR    8
JOR    8
BRA    8
BOL    8
BEL    8
ARM    8
BGD    8
BHR    8
AUT    8
AUS    8
ARG    8
CZE    8
DNK    8
DOM    8
ECU    8
KAZ    8
JPN    8
ITA    8
ISR    8
IRL    8
IRN    8
IDN    8
IND    8
ISL    8
HUN    8
HKG    8
HND    8
GTM    8
GRC    8
DEU    8
FRA    8
FIN    8
EST    8
SLV    8
SRB    8
Name: Reporting Economy ISO3A Code, dtype: int64

In [ ]:
#agora é hora de eliminar as colunas irrelevantes para a análise
df_wt3 = df_wt2['']