# Dados

Estrutura dos dados: (parte mais densa tecnicamente)
* importar os dados com o pacote pandas (3 bases de dados diferentes)
* incorporar as 3 bases de dados em uma tabela só 
* aprimorar a organização da tabela 
* pegar dados (primeiro os obrigatórios) da tabela
* apresentar eles de forma informativa (talvez gráficos)

In [1]:
import pandas as pd 
import html5lib

#não importei do kaggle, não consegui e não sei se dá pra abrir em qualquer pc sem ter nada instalado

url="https://github.com/talissonmeira/WTH/blob/main/WtoData_20221014064138.csv?raw=true"

df_data = pd.read_csv(url,encoding='latin-1')

C:\Users\Dell\AppData\Local\Temp\ipykernel_9152\2546019985.py:8: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_data = pd.read_csv(url,encoding='latin-1')

Os dados foram importados de um repositório público que eu criei no GitHub. As linhas com problemas foram substituídas por falsas, como são apenas 3 linhas em meio a 3 mil não vejo muito problema

In [4]:
pd.set_option('display.max_rows', 15)
df_data
#suario

,Indicator Category,Indicator Code,Indicator,Reporting Economy Code,Reporting Economy ISO3A Code,Reporting Economy,Partner Economy Code,Partner Economy ISO3A Code,Partner Economy,Product/Sector Classification Code,...,Period,Frequency Code,Frequency,Unit Code,Unit,Year,Value Flag Code,Value Flag,Text Value,Value
0,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,000,NaN,World,000,NaN,World,SITC3,...,Annual,A,Annual,IDP,Previous year=100,2021,NaN,NaN,NaN,126.432000
1,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,004,AFG,Afghanistan,000,NaN,World,SITC3,...,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,85.260000
2,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,008,ALB,Albania,000,NaN,World,SITC3,...,Annual,A,Annual,IDP,Previous year=100,2021,NaN,NaN,NaN,138.571000
3,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,012,DZA,Algeria,000,NaN,World,SITC3,...,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,104.676000
4,Merchandise trade - indices and prices,ITS_MTP_AM,Merchandise import value chained indices - annual,016,ASM,American Samoa,000,NaN,World,SITC3,...,Annual,A,Annual,IDP,Previous year=100,2021,E,Estimate,NaN,101.862000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97659,Trade in commercial services,ITS_CS_QX,Commercial services exports by main sector  q...,927,NaN,Euro Area (19),ZX9,NaN,Extra Euro Area (19) Trade,BOP6,...,First Quarter,Q,Quarterly,USM,Million US dollar,2022,NaN,NaN,NaN,15312.113403
97660,Trade in commercial services,ITS_CS_QX,Commercial services exports by main sector  q...,927,NaN,Euro Area (19),ZX9,NaN,Extra Euro Area (19) Trade,BOP6,...,First Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,13330.434057
97661,Trade in commercial services,ITS_CS_QX,Commercial services exports by main sector  q...,927,NaN,Euro Area (19),ZX9,NaN,Extra Euro Area (19) Trade,BOP6,...,Second Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,13603.131178
97662,Trade in commercial services,ITS_CS_QX,Commercial services exports by main sector  q...,927,NaN,Euro Area (19),ZX9,NaN,Extra Euro Area (19) Trade,BOP6,...,Third Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,13175.430665
97663,Trade in commercial services,ITS_CS_QX,Commercial services exports by main sector  q...,927,NaN,Euro Area (19),ZX9,NaN,Extra Euro Area (19) Trade,BOP6,...,Fourth Quarter,Q,Quarterly,USM,Million US dollar,2021,NaN,NaN,NaN,15603.408962